### ISSUE TITLE
storage: clean up

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#102]
Issue to track storage clean up and redesign

* [x] ~~Move improvements to a separate issue~~
  * ~~Now moved to: https://github.com/log2timeline/plaso/issues/568~~
* [x] ~~[Added collection information object](https://codereview.appspot.com/201160043/)~~
* [x] ~~[Added storage factory](https://codereview.appspot.com/199420043/)~~
* [x] ~~[Adding the storage helper](https://codereview.appspot.com/217820043/)~~
* [x] ~~[Split off writer to separate file](https://codereview.appspot.com/269970043)~~
  * ~~fix https://github.com/log2timeline/plaso/issues/351~~
* [x] ~~[move storage file from lib to storage](http://codereview.appspot.com/267200043)~~
  * ~~fixed flaky test testProcessStorageWithMissingParameters (due to static TimeRangeCache)~~
  * ~~also fixes sys.argv in psort front-end~~
* [x] ~~fix https://github.com/log2timeline/plaso/issues/56~~
  * ~~https://codereview.appspot.com/267520043/~~
  * ~~remove direct call to pfilter in psort front end~~
  * ~~clean up need for pfilter.TimeRangeCache.ResetTimeConstraints()~~
  * ~~check if [Unable to read from storage file in certain edge cases when a date filter is used #140](https://github.com/log2timeline/plaso/issues/140) is fixed~~
* [x] ~~[remove unused event group](http://codereview.appspot.com/279600043)~~
* [x] ~~[remove struct](https://codereview.appspot.com/282020043/)~~
* [x] ~~[remove store index from default plaso output](http://codereview.appspot.com/281530043)~~
* [x] ~~Implement StorageReader~~
  * clean up psort
* [x] ~~move pre_obj out of storage file~~
* [x] ~~[remove plaso_meta.# and storage_information.stores](https://codereview.appspot.com/289250043/)~~
  * ~~does not seem to be used anywhere outside pinfo~~
  * ~~Why have separate YAML serialization in the storage? - have 1 serialization format per file~~
* [x] ~~fix ambiguity/terminology~~ - somewhat fixed at least improved
  * ~~store number vs. stream number vs. proto number~~
  * ~~store index, store offset vs. entry index~~
  * ~~entry vs. ...~~
  * ~~proto vs. serialized data~~
* [x] ~~determine if EventBuffer is still needed~~ - yes
* [x] ~~separate concerns of managing objects, serialization, data storage and offset indexes, zip container, etc.~~
  * ~~[added data stream and offset table objects](https://codereview.appspot.com/262660043/)~~
  * ~~[added timestamp table object](https://codereview.appspot.com/267260043/)~~
    * ~~timestamp filter bug fix~~
  * ~~[separate serialization and stream management](https://codereview.appspot.com/273800043/)~~
    * ~~fix https://github.com/log2timeline/plaso/issues/8~~
* [x] ~~remove BypassStorageWriter~~

Notes:

Old comments found in zip_file.py
```
# TODO: Go through the storage library to see if it can be split in two, one
# part which will define the storage itself, and can be relatively independent.
# Independent enough to be split into separate project to ease integration by
# other tools. This file will then contain the queueing mechanism and other
# plaso specific mechanism, making it easier to import the storage library.
```

**Comment by joachimmetz** [comment]
I opt to fill the collection_information based on the "output" objects since with databased backed storage there is no output file.
```
collection_information['output_file'] = self._storage_file_path
```

**Comment by joachimmetz** [comment]
Remove direct access of formatter.format_string in output classes.

**Comment by kiddinn** [comment]
the format string output will be left out of the first CL, it is already growing to be almost too big, but since the storage is integrated into several places in the core it is necessary to have the first CL rather large.

Then following will be few clean up CL's, making sure things are all WAI,.

**Comment by kiddinn** [comment]
the first CL will hopefully soon be ready, storage is working, psort is working fully, just locating all libraries that interact with storage and making changes, then clean-up of doc strings, etc and upload.

**Comment by kiddinn** [comment]
first CL in: http://codereview.appspot.com/200180043

This is still a WIP (as of this moment).

**Comment by kiddinn** [comment]
So far:

  + Added a CollectionInformation object (currently stored with the knowledge base, unclear if that is the best location)
  + Removed the use of pre_obj in several places in favor of directly using the knowledge_base
  + Added a separate interface file for the storage layer
  + Added one implementation of the interface, pstorage
  + Fixed all front-ends and other code to work with the new interface
  + When CL is ready, all doc strings and tests are going to be in.

Next step:

 + Complete all checks for front-ends that accept arbitrary storage files for reading so that they check all implementations before bailing out
 + Fix some nuances in the current CL (TODO's added)
 + Provide a mechanism to insert custom settings into each storage implementation (eg: buffer size for pstorage, serialization format for pstorage, database information for a database file, etc)
 + Re-enable the storage bypass by implementing a storage file that uses the output modules for it's output

What is then next after those next steps:

 + Create a new storage layer that is faster than pstorage, first attempt SQLite but other storage solutions are also being explored.

**Comment by kiddinn** [comment]
and BTW the first CL that comes out still has some nuances (as mentioned in previous comments), such as the fact that it still relies on the storage file to be a file path, not a file like object or any other form.

**Comment by kiddinn** [comment]
Other CL has been redacted in favor of splitting this up into smaller CL's

CL 1: https://codereview.appspot.com/201160043/ - adding collection information object
CL 2: https://codereview.appspot.com/199420043/ - adding storage factory

**Comment by kiddinn** [comment]
For now, code will be added but the new storage will not be integrated into the main tool at this point. First step will be to commit all the new parts independently and then finally making the actual changes in the main tool.

**Comment by kiddinn** [comment]
Closing #119 with the addition of this comment here:
 + Presently, we have a parser error queue, but errors are not written to storage, but are silently discarded. It would be better if we actually wrote these to storage.

**Comment by kiddinn** [comment]
Code review: https://codereview.appspot.com/217820043/ - adding the storage helper

**Comment by joachimmetz** [comment]
Also see: https://github.com/log2timeline/plaso/issues/8

**Comment by joachimmetz** [comment]
Additional points taken from roadmap:

  * Add support for relocatable path specs
  * Add support to keep a protected copy of the decryption information for e.g. BitLocker

**Comment by joachimmetz** [comment]
Why have separate YAML serialization in the storage? I opt to stick with 1 serialization format per storage file.

**Comment by joachimmetz** [comment]
Add fake storage for faster testing.

**Comment by joachimmetz** [comment]
Moved open points to https://github.com/log2timeline/plaso/issues/338, closing issue
