### ISSUE TITLE
winreg: clean up and improve

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#145]
- [x] ~~preparations~~
  - ~~[Clean up of Windows preprocessor plugins](https://codereview.appspot.com/250920043/)~~
- [x] ~~[Step 1](https://codereview.appspot.com/255830043/)~~
- [x] ~~[Step 2](https://codereview.appspot.com/257750043/)~~
  - ~~removed cache~~
  - ~~renamed to dfwinreg~~
- [x] ~~[Step 3](https://codereview.appspot.com/259910043/)~~
  - ~~merge key and value plugins into single plugin type~~
  - ~~clean up MRU list plugins~~
- [x] ~~[Step 4](https://codereview.appspot.com/267850043/)~~
  - ~~do not pass key as kwargs, make sure key is set~~
  - ~~clean up: officemru, outlook, terminal_server, typedurls and winrar generate 1 Registry event for the whole MRU~~
- [x] ~~[Step 5](https://codereview.appspot.com/267930043/)~~
  - ~~replaced Registry type by key path prefix in plugins~~
- [x] ~~[Step 6](https://codereview.appspot.com/269610043/) - separate and remove plaso specifics~~
  - ~~expansion notation replace {...} by %...%~~
  - ~~use Windows path separators~~
  - ~~move Registry file reader implementations out of dfwinreg~~
- [x] ~~[Step 7 - Clean up](https://codereview.appspot.com/274160043/)~~
  - ~~remove OpenFileEntry - replace _GetKeyFromFileEntry in tests~~
  - ~~remove ExpandKeyPath~~
  - ~~make OpenFile private/protected?~~
  - ~~remove backend~~
  - ~~expose MapFile~~
  - ~~[remove _OpenREGFRegistryFile](https://github.com/log2timeline/plaso/issues/389)~~
- [x] ~~[Step 8](https://codereview.appspot.com/267650043/) - move data to GetData() and raw_data to data~~
- [x] ~~Step 9 - split of winreg into a stand-alone module to handle Windows Registry~~
  - ~~move to https://github.com/log2timeline/dfwinreg~~
  - ~~migrate [winreg-kb](https://github.com/libyal/winreg-kb) to use dfwinreg~~
  - ~~clean up and test dfwinreg with winreg-kb~~
- [x] ~~Step 10 - [remove dfwinreg from plaso](https://github.com/joachimmetz/plaso/tree/dfwinreg)~~
- [x] ~~Step 11 - [build a key path filter tree for faster matching plugins with key paths](http://codereview.appspot.com/277550043)~~
  - ~~add scan tree-based path filter~~
- [x] ~~Have plugins create type specific events~~
  - ~~Move URLs to formatting phase?~~
- [x] ~~Remove source append in winreg plugins~~
- [x] ~~ServicesPlugin add key path prefix support~~ - moved to https://github.com/log2timeline/plaso/issues/2636
- [x] ~~[preg clean up refactor](https://github.com/log2timeline/plaso/issues/365)~~
- [x] ~~rename WindowsRegistryEvent to WindowsRegistryKeyEvent ?~~ is WindowsRegistryEventData now
- [x] ~~task_scheduler add regex subkey name check instead of using data size~~ - moved to https://github.com/log2timeline/plaso/issues/2637
- [x] ~~move Registry to a separate collection phase?~~ - moved to https://github.com/log2timeline/plaso/issues/2638
  - ~~allow for live Registry analysis?~~ 
- [x] ~~add support for is corrupt flag~~ - moved to https://github.com/log2timeline/plaso/issues/2639
- [x] ~~use find spec equivalent for key paths to also support regexp~~ - findspecs part of dfWinReg and used by artifacts filter
- [x] ~~is WinRegistryKeyPathExpander still needed? if not remove~~
- [x] ~~plaso/engine/utils.py remove PathExpander? if not add tests~~
- [x] ~~remove Registry type~~
- [x] ~~Tests use full Registry key paths e.g. HKLM~~
- [x] ~~scan tree-based path filter double check if remainder list is used correctly in scan tree initialization~~ - moved to https://github.com/log2timeline/plaso/issues/2640
- [x] ~~make sure return value of GetDataAsObject is checked~~ - moved to https://github.com/log2timeline/plaso/issues/2641
