### ISSUE TITLE
Change how analysis reports are stored

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1590]
Change how analysis reports are stored. Some analysis plugins exceed the imposed limit of memory since the analysis report is written at the end.

What should be the role of the analysis report should be versus event tags?
* is the role of the analysis report to provide a summary?

Different types of analysis plugins:
* those that are used to create a summary / overview
  * have some means store entries without large memory overhead
  * entries are analysis results attribute containers
* those that are used to "enrich" events
  * is a summary of the enrichment sufficient, such as the number of events tagged?
  * store the enriched data in such a way that can be outputted as part of the event values? use event tags?
* others
  * general summary of the analysis plugin running and number of events analyzed?

Have analysis plugins store results and have pinfo print report of these result attribute containers:

* [x] ~~https://github.com/log2timeline/plaso/issues/1090~~ - obsolete since pinfo will take care of the formatting from now on
* [x] ~~From https://github.com/log2timeline/plaso/issues/366 analysis report object fix docstring~~ - not fixed but report dict is now no longer used and deprecated
* [x] ~~From https://github.com/log2timeline/plaso/issues/1148 remove the need for report_dict~~ - https://github.com/log2timeline/plaso/issues/3981
* [x] browser search - https://github.com/log2timeline/plaso/pull/3976
* [x] chrome extensions - https://github.com/log2timeline/plaso/pull/3977
* [x] hash tagging/nsrlsvr/viper/virustotal - https://github.com/log2timeline/plaso/pull/3979
* [x] sessionize - https://github.com/log2timeline/plaso/pull/3980
* [x] tagging - https://github.com/log2timeline/plaso/pull/3982
* [x] unique_domains_visited - https://github.com/log2timeline/plaso/pull/3984
* [x] windows_services - replace by preprocessing plugin - https://github.com/log2timeline/plaso/pull/3992

**Comment by Onager** [comment]
What's broken presently?

**Comment by joachimmetz** [comment]
Good question, I copied this from an earlier bug but I need to revisit my notes. I think this is related to analysis reports being stored as unformatted or formatted text

**Comment by Onager** [comment]
Bumping from milestone, as this isn't well defined yet.

**Comment by joachimmetz** [comment]
One thing that is currently broken is analysis plugins maintaining in memory list of items to report on. Either we ensure reports remain small or find a way to incrementally store report entries.

**Comment by joachimmetz** [comment]
remove the need for report_dict. This is currently used by 

* browser_search
* chrome_extension, to report about extensions per user

**Comment by joachimmetz** [comment]
Have analysis plugins store results and have pinfo print report of these result attribute containers
