### ISSUE TITLE
Code clean up

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#160]
- [x] ~~move dependencies to dfvfs/dependencies~~
- [x] ~~[move tests to separate directory](https://codereview.appspot.com/236520044/)~~
- [x] ~~move tools tests~~ - task abandoned causes import issues
- [x] ~~fix names and email addresses in commit history~~
- [x] ~~[Removed the default is from docstrings where not needed](https://codereview.appspot.com/284890043/)~~
- [x] ~~add tests for bencode plugins~~
- [x] ~~[Moved test cases to single base test case](https://codereview.appspot.com/300010043/)~~
- [x] ~~[remove utils.GetUnicodeString](https://codereview.appspot.com/303220043/)~~
- [x] ~~remove errors.NotAText only used by opera parser~~
- [x] ~~move version checks into dependencies so that the version info is in one place~~
  - ~~libyal, https://codereview.appspot.com/240360043~~
  - ~~sqlite~~
- [x] ~~Clean up parsers~~
  - ~~firefox_cache~~
- [x] ~~replace Utf16StreamCopyToString by in parser utf16 conversion to localize parser errors~~
- [x] ~~Implement a ToString functions that replace `__str__` and `__unicode__`~~
  - ~~`__str__` is only used in filters moving this to https://github.com/log2timeline/plaso/issues/324~~
- [x] ~~Make docstrings consistent~~
- [x] ~~make client protected https://codereview.appspot.com/315530043/diff/20001/plaso/output/elastic.py~~
- [x] ~~add pass to empty classes~~ - pylint now enforces to not do this
  * ~~https://codereview.appspot.com/326740043/diff/60001/tests/cli/tool_options.py?context=10&column_width=80~~
- [x] ~~move `def _GetTestFilePath(self, path_segments):` to main test_lib~~
  - ~~largely in main test lib now~~
- [x] ~~Replace e.g. by "for example" or "such as"~~
  - ~~update [style guide](https://github.com/log2timeline/l2tdocs/blob/master/process/Style-guide.md#docstrings)~~
  - ~~update code: https://github.com/log2timeline/plaso/pull/2700~~
- [x] ~~remove LinearOutputModule - https://github.com/log2timeline/plaso/pull/3369~~
- [x] ~~Fix import order, add comment why pytz is not following the style guide - https://github.com/log2timeline/plaso/pull/3373~~
- [x] ~~Clean up `_ParsePerformanceOptions` - moved to https://github.com/log2timeline/plaso/issues/3394~~
- [x] ~~use decode(encoding, errors='replace') instead of decode(encoding, errors='ignore')~~
- [x] ~~assertTrue or assertFalse containing is (not) None~~
- [x] ~~plaso/analysis/interface.py replace tag_strings by better alternative e.g. labels~~
- [x] ~~make data_location public class attribute in tools, also see https://codereview.appspot.com/150170043/diff/120001/plaso/cli/helpers/artifact_definitions.py - moved to https://github.com/log2timeline/plaso/issues/3502~~
- [x] ~~add cli arg helper for `_ParseLogFileOptions` - moved to https://github.com/log2timeline/plaso/issues/3504~~~
- [x] ~~use textwrap.dedent instead of arrays for CLI text - moved to https://github.com/log2timeline/plaso/issues/3505~~
- [x] ~~clean up psteal tests - moved to https://github.com/log2timeline/plaso/issues/3506~~
  * https://codereview.appspot.com/326740043/diff/60001/tests/cli/psteal_tool.py?context=10&column_width=80

**Comment by Onager** [comment]
Please do not re-add to milestone. Break this ticket up into individual pieces of clean up, and then add those to milestones instead.
