### ISSUE TITLE
Add structural fix for session parser counter

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1691]
session parser counter not being filled, work around in https://github.com/log2timeline/plaso/issues/1687, but this needs structural fix:

* [x] move the parser attribute to event data - https://github.com/log2timeline/plaso/pull/3639
* [x] add tests https://github.com/log2timeline/plaso/pull/3698
* [x] ~~rename parser to parser_chain~~ - moved to https://github.com/log2timeline/plaso/issues/3700

**Comment by Onager** [comment]
We also need to work out what we actually want to count here - events, eventdatas, both?

**Comment by Onager** [comment]
@joachimmetz Can you elaborate on what needs the structural fix here? It's not clear to me what the structural issue is.

**Comment by joachimmetz** [comment]
@Onager good question, I'll need to jog my memory

**Comment by joachimmetz** [comment]
A comment in https://codereview.appspot.com/338420043/diff/1/plaso/parsers/mediator.py that seem to have dropped over time:
```
# TODO: rename this to event.parser_chain or equivalent.
```

**Comment by joachimmetz** [comment]
An idea might have been to add counters based on the full parser chain instead of the last parser in the chain. I don't recall at this time. So maybe:

* rename parser to parser_chain
* add tests

**Comment by joachimmetz** [comment]
Address comment in https://github.com/log2timeline/plaso/blob/master/plaso/parsers/mediator.py#L510

* move the parser attribute to event data
* make sure parser counters are updated and working

**Comment by joachimmetz** [comment]
Changes https://github.com/log2timeline/plaso/pull/3639 to address moving the parser attribute to event data

**Comment by joachimmetz** [comment]
> We also need to work out what we actually want to count here - events, eventdatas, both?

Keeping what we count as-is, number of events extracted/generated by parser or parser plugin
