### ISSUE TITLE
Misc issues - RC testing

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#218]
This is a place holder issue for issues uncovered while pre RC testing see below for detailed information.

* [x] test for psort time slice

Completed

* [x] ~~preg broken: #236~~
* [x] ~~IndexError -> list index out of range in ASL parser~~
* [x] ~~firefox_old_cache fix missing explicit close and code clean up~~
* [x] ~~Add filename to error: `Unsupported Custom Destination file - invalid entry header.` - https://codereview.appspot.com/240480043/~~
* [x] ~~Improve liblnk - bug fix~~
* [x] ~~check if Python logger appends or truncates existing log file by default - also what should be the desired behavior IMO truncate - https://codereview.appspot.com/243200043/~~
* [x] ~~flaky rawpy test https://github.com/log2timeline/plaso/issues/232~~
* [x] ~~fix non-explicit close winreg - https://codereview.appspot.com/245980043/~~
* [x] ~~error logged in timelib - https://codereview.appspot.com/245190043/~~
* [x] ~~add support for '--parsers list' https://github.com/log2timeline/plaso/issues/120~~
* [x] ~~expose SIGSEGV handler for debugging purposes - http://codereview.appspot.com/240570043~~
* [x] ~~Fix the partition selection~~
* [x] ~~issue in pinfo #237~~
* [x] ~~make status view window work for Windows - https://codereview.appspot.com/242200043/~~
* [x] ~~Added missing license files - http://codereview.appspot.com/244270043~~
* [x] ~~Display name add VSS support - needed for trouble shooting - https://codereview.appspot.com/241430043/~~
* [x] ~~changes in ASL parser for better exception handling: http://codereview.appspot.com/248800043~~
* [x] ~~Add parser information to the "Unable to process path spec" bug if possible to make debugging easier~~
* [x] ~~SIGSEGV in libvshadow - memory corruption was (very likely) caused somewhere else~~
* [x] ~~Improve libfwsi - at least sufficient for now~~
* [x] check why Windows tests are flaky https://ci.appveyor.com/project/joachimmetz/plaso/build/146
  * ~~RPC needs a bit more time to establish channels~~
* [x] ~~fix non-explicit closes - https://codereview.appspot.com/246090043/~~
* [x] ~~Fix issue with source scanner https://github.com/log2timeline/plaso/issues/229~~
* [x] ~~Add BDE support https://github.com/log2timeline/plaso/issues/109~~
* [x] ~~viper analysis plugin - https://codereview.appspot.com/246500043/~~
* [x] ~~chrome_cache did not explicitly close file-object for file - https://codereview.appspot.com/250130043/~~
* [x] ~~Improve BDE support https://github.com/log2timeline/plaso/issues/109~~

Won't fix (Unlikely to be fixed before release)

* [ ] TSK issues - though try to find a solution/root cause if time permits
  * NTFS related [SIGSEGV in libtsk](https://github.com/sleuthkit/sleuthkit/issues/462)
  * HFS issues: https://github.com/sleuthkit/sleuthkit/issues/401, https://github.com/sleuthkit/sleuthkit/issues/471
  *  source scanner caused loop in libtsk - could the non-POSIX behavior of TSK be the root cause?

**Comment by joachimmetz** [comment]
```
[WARNING] [firefox_old_cache] did not explicitly close file-object for path specification:
```

**Comment by joachimmetz** [comment]
```
Traceback (most recent call last):
  File "plaso/engine/worker.py", line 169, in _ParseFileEntryWithParser
    parser_object.UpdateChainAndParse(self._parser_mediator)
  File "plaso/parsers/interface.py", line 72, in UpdateChainAndParse
    self.Parse(parser_mediator, **kwargs)
  File "plaso/parsers/interface.py", line 256, in Parse
    self.ParseFileObject(parser_mediator, file_object, **kwargs)
  File "plaso/parsers/custom_destinations.py", line 142, in ParseFileObject
    lnk_file_object = resolver.Resolver.OpenFileObject(path_spec)
  File "dfvfs/resolver/resolver.py", line 113, in OpenFileObject
    file_object.open(path_spec=path_spec)
  File "dfvfs/file_io/file_io.py", line 75, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "dfvfs/file_io/data_range_io.py", line 90, in _Open
    path_spec.parent, resolver_context=self._resolver_context)
  File "dfvfs/resolver/resolver.py", line 113, in OpenFileObject
    file_object.open(path_spec=path_spec)
  File "dfvfs/file_io/file_io.py", line 75, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "dfvfs/file_io/tsk_file_io.py", line 62, in _Open
    self._tsk_file = file_entry.GetTSKFile()
AttributeError: 'NoneType' object has no attribute 'GetTSKFile'
```

**Comment by joachimmetz** [comment]
```
File-object not explicitly closed for file: TSK:/Users/$USERNAME/AppData/Local/Microsoft/Windows/UsrClass.dat
```

**Comment by joachimmetz** [comment]
```
pyolecf_property_set_stream_get_set: unable to retrieve property set.
libolecf_property_value_read_data: unsupported property value type: 0x0000002f.
libolecf_property_section_read: unable to read property value: 50 at offset: 1660.
libolecf_property_set_read: unable to read property section: 1 at offset: 132.
libolecf_property_set_stream_get_set: unable to read property set.
```

**Comment by joachimmetz** [comment]
```
pyfwsi_item_list_copy_from_byte_stream: unable to copy from byte stream.
libfwsi_extension_block_copy_from_byte_stream: byte stream size exceeds maximum.
libfwsi_item_copy_from_byte_stream: unable to copy byte stream to extension block.
libfwsi_item_list_copy_from_byte_stream: unable to copy byte stream to shell item.
```

**Comment by kiddinn** [comment]
Still some issues with filehandles not properly closed. This is taken from one of the Mac test images:

    2015-06-08 19:59:03,495 [WARNING] (Worker_07 ) PID:20048 <worker> File-object not explicitly closed for file: TSK:/.DocumentRevisions-V100/PerUID/501/5/com.apple.documentVersions/A66C960A-4399-4DBA-89FF-4BE6FF9E5A74.pdf

This is then followed by:

    with error: pysigscan_scanner_scan_file_object: unable to scan file. pysigscan_file_object_read_buffer: unable to read from file object with error: 'File_read_random:  (tsk3.c:494) Read error: Attribute not found in file (tsk_fs_attrlist_get: Attribute 4352 not found)'. pysigscan_file_object_io_handle_read: unable to read from file object. libbfio_handle_read_buffer: unable to read from handle. libsigscan_scanner_scan_file_io_handle: unable to read buffer.

Same error comes up quite a few time during the processing of the image.

Another error originating from the same image:

    2015-06-08 22:42:36,682 [WARNING] (Worker_06 ) PID:20045 <worker> Unable to process path spec: type: OS, location: /<imagepath.e01>
    type: EWF
    type: TSK, inode: 290287, location: /System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/test/test_zipimport.pyc
     with error: Invalid offset value less than zero.

This is also repeated quite a few times.

Issues here:

- [ ] Find and fix the explicit file close that needs to be added.
- [ ] Find what is causing the "invalid offset value" error.

**Comment by kiddinn** [comment]
Another random error in logs (408 challenge image):

    <timelib> Unable to copy .google.com /search/ to a datetime object with error: unknown string format

Unknown origin, need to track that one down.

**Comment by joachimmetz** [comment]
```
[winreg/userassist] unable to parse file: TSK:/Users/$USERNAME/NTUSER.DAT with error: Unsupported value data size: 1612
```

**Comment by joachimmetz** [comment]
```
#.automaticDestinations-ms

pylnk_file_get_volume_label: unable to retrieve UTF-8 volume label.
libuna_utf8_string_with_index_copy_from_utf16_stream: missing UTF-16 stream bytes.
liblnk_file_get_utf8_volume_label: unable to set UTF-8 volume label string.
```

**Comment by kiddinn** [comment]
Using --partition 2 gets me the traceback:

Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 611, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 597, in Main
    tool.ProcessSources()
  File "/usr/bin/log2timeline.py", line 531, in ProcessSources
    self.ScanSource(self._front_end)
  File "/usr/lib/python2.7/dist-packages/plaso/cli/storage_media_tool.py", line 724, in ScanSource
    location = u'/{0:s}'.format(partition_identifier)
ValueError: Unknown format code 's' for object of type 'int'


Changing this to a decimal value now reveals:

2015-06-09 15:46:46,665 [WARNING] (MainProcess) PID:15279 <log2timeline> Invalid or missing volume scan node.

Fix on the way

**Comment by kiddinn** [comment]
The last one should be covered in: https://codereview.appspot.com/246830043/

**Comment by kiddinn** [comment]
Status view = window on Windows has minor issues with extra characters added:
Version:
←[2J←[Hplaso - log2timeline version 1.3.0_20150607
Column:
←[1mIdentifier  PID     Status          Events          File←[0m

**Comment by kiddinn** [comment]
If you run the tool against a disk image that has VSS stores on them and you supply the --no-vss parameter nothing will get parsed:

     <log2timeline> No supported file system found in source.

**Comment by kiddinn** [comment]
the `_ScanVolume` inside the storage_media_tool is not handling this properly.

If there is a VSS scan node the TSK current volume scan node is not moved to the same level as the VSS one is in the case where VSS is not processed.

Fixed in https://codereview.appspot.com/246830043/

**Comment by kiddinn** [comment]
Running against nfury image I see a lot of:

    2015-06-09 20:49:12,072 **ERROR** (Worker_03 ) PID:44042 <mediator> **chrome_cache** unable to parse file: TSK:/Users/nfury/AppData/Local/Google/Chrome/User Data/Default/Cache/index with error: Missing data block file: data_1


    2015-06-09 20:49:12,076 **ERROR** (Worker_03 ) PID:44042 <mediator> **chrome_cache** unable to parse file: TSK:/Users/nfury/AppData/Local/Google/Chrome/User Data/Default/Cache/index with error: Cache address: 0xa1010dde missing data file.

**Comment by kiddinn** [comment]
Seeing few of these:

    2015-06-10 18:02:26,827 ERROR] (Worker_12 ) PID:23453 <mediator> [mcafee_protection] unable to parse file: TSK:/Users/Susan Storm Richards/AppData/LocalLow/Google/FastSearch/dictionaries/dictionaries.txt with error: Unable to parse time string: .google.com /search/

**Comment by kiddinn** [comment]
Also tracking #237

**Comment by kiddinn** [comment]
One of the Mac test images:

```
2015-06-11 20:34:20,397 [WARNING] (Worker_14 ) PID:18236 <worker> Unhandled exception while processing path spec: type: OS, location: /<PATH>.E01
type: EWF
type: TSK_PARTITION, location: /p2, part index: 5, start offset: 0x0c805000
type: TSK, inode: 542723, location: /System/Library/Caches/com.apple.kext.caches/Startup/KextPropertyValues_OSBundleHelper_x86_64.plist.gz
type: GZIP
.
2015-06-11 20:34:20,397 [ERROR] (Worker_14 ) PID:18236 <worker> Maximum number of cached values reached.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 417, in _ProcessPathSpec
    path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 53, in OpenFileEntry
    path_spec, resolver_context=resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 163, in OpenFileSystem
    file_system.Open(path_spec=path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/file_system.py", line 234, in Open
    self._resolver_context.CacheFileSystem(path_spec, self)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/context.py", line 62, in CacheFileSystem
    self._file_system_cache.CacheObject(identifier, file_system)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/cache.py", line 83, in CacheObject
    raise errors.CacheFullError(u'Maximum number of cached values reached.')
CacheFullError: Maximum number of cached values reached.
```

**Comment by kiddinn** [comment]
Same Mac image:

```
2015-06-11 16:38:08,096 [WARNING] (Worker_08 ) PID:18223 <worker> File-object not explicitly closed for file: TSK:/.DocumentRevisions-V100/PerUID/501/2/com.apple.documentVersions/3C43F7DD-4BC7-4B22-99FD-
192CE21E21A8.rtf
2015-06-11 16:38:08,097 [WARNING] (Worker_08 ) PID:18223 <worker> Unable to process path spec: type: OS, location: <PATH>.E01
type: EWF
type: TSK_PARTITION, location: /p2, part index: 5, start offset: 0x0c805000
type: TSK, inode: 672541, location: /.DocumentRevisions-V100/PerUID/501/2/com.apple.documentVersions/3C43F7DD-4BC7-4B22-99FD-192CE21E21A8.rtf
 with error: pysigscan_scanner_scan_file_object: unable to scan file. pysigscan_file_object_read_buffer: unable to read from file object with error: 'File_read_random: (tsk3.c:494) Read error: Attribute 
not found in file (tsk_fs_attrlist_get: Attribute 4352 not found)'. pysigscan_file_object_io_handle_read: unable to read from file object. libbfio_handle_read_buffer: unable to read from handle. libsigsc
an_scanner_scan_file_io_handle: unable to read buffer.
```

This comes from:

    plaso - log2timeline version 1.3.0_20150610

**Comment by kiddinn** [comment]
This message is repeated quite frequently, sometimes as:
```2015-06-11 16:38:08,563 [WARNING] (Worker_14 ) PID:18236 <worker> File-object not explicitly closed for file: GZIP:/.fseventsd/000000000006ed2b```

but all over the log files

**Comment by kiddinn** [comment]
These errors (both the Mac OS X ones) appear quite frequently in all Mac OS X parsing, need to go over the Mac OS X parsers and make sure the explicitly close filehandles.

 - [ ] Make sure Mac OS X parsers close filehandles
 - [ ] Find out what parser is behind the CacheFullError

**Comment by kiddinn** [comment]
Other issues with another Mac OS X image being parsed:

```
2015-06-11 08:36:59,200 [WARNING] (Worker_12 ) PID:8866 <worker> Unable to process path spec: type: OS, location: /<PATH>.E01
type: EWF
type: TSK_PARTITION, location: /p2, part index: 5, start offset: 0x0c805000
type: TSK, inode: 531208, location: /Applications/iPhoto.app/Contents/Resources/Themes/Shared/Card/ModernOrnaments/Orn-Red.png
 with error: Invalid offset value less than zero.
```

And

```
2015-06-11 08:43:38,546 [WARNING] (Worker_08 ) PID:8858 <worker> Unable to process path spec: type: OS, location: <PATH>.E01
type: EWF
type: TSK_PARTITION, location: /p2, part index: 5, start offset: 0x0c805000
type: TSK, inode: 450919, location: /Applications/iTunes.app/Contents/Resources/Japanese.lproj/Localizable.strings
 with error: File_read_random: (tsk3.c:494) Read error: Error reading image file ( zlib_inflate: zlib returned error -5 ((null))) ( hfs_attr_walk_special: zlib inflation (uncompression) failed)
```

This zlib error comes up quite a few times in the logs

```
2015-06-11 10:03:06,913 [WARNING] (Worker_05 ) PID:8851 <worker> Unhandled exception while processing path spec: type: OS, location: <PATH>E01
type: EWF
type: TSK_PARTITION, location: /p2, part index: 5, start offset: 0x0c805000
type: TSK, inode: 676714, location: /private/var/log/asl/2013.12.17.U0.G80.asl
.
2015-06-11 10:03:06,914 [ERROR] (Worker_05 ) PID:8851 <worker> list index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 425, in _ProcessPathSpec
    self._ProcessFileEntry(file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 382, in _ProcessFileEntry
    self._ParseFileEntryWithParser(parser_object, file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 200, in _ParseFileEntryWithParser
    parser_object.UpdateChainAndParse(self._parser_mediator)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/interface.py", line 72, in UpdateChainAndParse
    self.Parse(parser_mediator, **kwargs)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/interface.py", line 256, in Parse
    self.ParseFileObject(parser_mediator, file_object, **kwargs)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/asl.py", line 205, in ParseFileObject
    event_object, offset = self.ReadAslEvent(file_object, offset)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/asl.py", line 347, in ReadAslEvent
    message = values[3]
IndexError: list index out of range
```
And finally:

```
2015-06-11 08:01:00,508 [WARNING] (Worker_09 ) PID:4788 <worker> File-object not explicitly closed for file: COMPRESSED_STREAM:/Users/<USERNAME>/Downloads/Firefox 26.0.dmg
2015-06-11 08:01:00,509 [WARNING] (Worker_09 ) PID:4788 <worker> Unhandled exception while processing path spec: type: OS, location: <PATH>.E01
type: EWF
type: TSK, inode: 380562, location: /Users/<USERNAME>/Downloads/Firefox 26.0.dmg
type: COMPRESSED_STREAM, compression_method: bzip2
.
2015-06-11 08:01:00,412 [ERROR] (Worker_01 ) PID:4773 <worker> Unable to decompress bzip2 compressed stream with error: end of stream was already found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 425, in _ProcessPathSpec
    self._ProcessFileEntry(file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 353, in _ProcessFileEntry
    self._HashFileEntry(file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 143, in _HashFileEntry
    if not file_entry.IsFile() or not self._hasher_names:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/file_entry.py", line 181, in IsFile
    self._stat_object = self._GetStat()
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/compressed_stream_file_entry.py", line 33, in _GetStat
    stat_object.size = compressed_stream.get_size()
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 314, in get_size
    self._uncompressed_stream_size = self._GetUncompressedStreamSize()
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 90, in _GetUncompressedStreamSize
    read_count = self._ReadCompressedData(self._COMPRESSED_DATA_BUFFER_SIZE)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 173, in _ReadCompressedData
    self._decompressor.Decompress(self._compressed_data))
  File "/usr/lib/python2.7/dist-packages/dfvfs/compression/bzip2_decompressor.py", line 43, in Decompress
    u'{0:s}.').format(exception))
BackEndError: Unable to decompress bzip2 compressed stream with error: end of stream was already found.
```

Fix:

 - [ ] IndexError -> list index out of range in ASL parser
 - [ ] Figure out and fix the Zlib error that comes up (compression error) - or handle that better
 - [ ] Fix bug with: "Invalid offset value less than zero"
 - [ ] Add parser information to the "Unable to process path spec" bug if possible to make debugging easier
 - [ ] Fix the BackEndError for bzip2 error (EOS was already found)

**Comment by kiddinn** [comment]
Minor CL for handling the ASL exception better: http://codereview.appspot.com/248800043

**Comment by kiddinn** [comment]
All Mac enabled parsers still seem to have an explicit close operation (most inherit from `SingleFileBaseParser`).

The invalid offset function is when a seek operation is attempted with a <0 offset value (after calculations based on the whence value)

Older ToDo's set in a task list:

 - [x] Fix the partition selection
 - [ ] Fix extra characters in the Window status view on Windows

**Comment by kiddinn** [comment]
Running VT analysis plugin always yields this:

```
[INFO] Plugin: [virustotal] started.
[INFO] Starting new HTTPS connection (1): www.virustotal.com
/Library/Python/2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

**Comment by Onager** [comment]
Per the link in the message, this occurs in Python < 2.7.9 Do we have a minimum version of python we support?

An alternate fix is to install some extra dependencies (pyopenssl and friends). I'm not wild about adding yet more dependencies though.

**Comment by Onager** [comment]
The not-completing sounds like a separate problem though. What do the status updates say? Is the number of queued items decreasing?

**Comment by kiddinn** [comment]
Hi

I'll reply better when at home but this is mac os x Yosemite, standard
Python.

Psort does indicate all output processing is done, all events are stored in
output file but the tool doesn't exit. I'm letting it run for some time
now, will check later today whether it really doesn't exit or if it just
takes really long too (as in way after all output processing).

**Comment by Onager** [comment]
Ah. If it's being run with a free API key it's going to take a very long
time (~20 hours or so). You should get updates that tell you this, and give
you an estimated time to completion.

**Comment by kiddinn** [comment]
So a quick update:

Mac OS X: Yosemite (10.10.3)
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin

We do not want to require a higher version of Python than the system supplied one.

I've now been running psort for about five hours and it still has not completed (4 1/2 since all output processing completed). So I can say that the processing is most likely stuck and will never complete due this error (which is the only sign of any activity, this error comes up every minute or so).

And this is not running with the free API key, but a purchased one. And I'm not getting any updates anywhere in the tool, the only information I'm getting is this repeated error message. This may warrant a separate issue rather than being appended to this one.

**Comment by kiddinn** [comment]
And having tcpdump enabled listening for connections to VT there is literally no traffic to their network. So it's not like the tool is slowly pushing packets there.

We would either need to disable the VT plugin for the Mac OS X platform or add the new dependencies.

**Comment by kiddinn** [comment]
When I finally "Ctrl+C" the process it completes with this traceback:

```
^CProcess Analysis virustotal:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150612-py2.7.egg/plaso/analysis/interface.py", line 110, in RunPlugin
    analysis_report = self.CompileReport(analysis_mediator)
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150612-py2.7.egg/plaso/analysis/interface.py", line 330, in CompileReport
    timeout=self._analysis_queue_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Queue.py", line 177, in get
    self.not_empty.wait(remaining)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 358, in wait
    _sleep(delay)
KeyboardInterrupt
```

That is, suggesting this is happening in the CompileReport stage (```analysis_report = self.CompileReport(analysis_mediator)```), in this piece of code:

```(python)
    while self._ContinueReportCompilation():
      try:
        self._LogProgressUpdateIfReasonable()
        hash_analysis = self.hash_analysis_queue.get(
            timeout=self._analysis_queue_timeout)
      except Queue.Empty:
```

Could this still be a queueing issue rather than being connected to the warning message.

**Comment by joachimmetz** [comment]
**Open**

```
2015-06-11 08:01:00,508 [WARNING] (Worker_09 ) PID:4788 <worker> File-object not explicitly closed for file: COMPRESSED_STREAM:/Users/<USERNAME>/Downloads/Firefox 26.0.dmg
2015-06-11 08:01:00,509 [WARNING] (Worker_09 ) PID:4788 <worker> Unhandled exception while processing path spec: type: OS, location: <PATH>.E01
type: EWF
type: TSK, inode: 380562, location: /Users/<USERNAME>/Downloads/Firefox 26.0.dmg
type: COMPRESSED_STREAM, compression_method: bzip2
.
2015-06-11 08:01:00,412 [ERROR] (Worker_01 ) PID:4773 <worker> Unable to decompress bzip2 compressed stream with error: end of stream was already found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 425, in _ProcessPathSpec
    self._ProcessFileEntry(file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 353, in _ProcessFileEntry
    self._HashFileEntry(file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 143, in _HashFileEntry
    if not file_entry.IsFile() or not self._hasher_names:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/file_entry.py", line 181, in IsFile
    self._stat_object = self._GetStat()
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/compressed_stream_file_entry.py", line 33, in _GetStat
    stat_object.size = compressed_stream.get_size()
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 314, in get_size
    self._uncompressed_stream_size = self._GetUncompressedStreamSize()
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 90, in _GetUncompressedStreamSize
    read_count = self._ReadCompressedData(self._COMPRESSED_DATA_BUFFER_SIZE)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 173, in _ReadCompressedData
    self._decompressor.Decompress(self._compressed_data))
  File "/usr/lib/python2.7/dist-packages/dfvfs/compression/bzip2_decompressor.py", line 43, in Decompress
    u'{0:s}.').format(exception))
BackEndError: Unable to decompress bzip2 compressed stream with error: end of stream was already found.
```

**Comment by rodgermoore** [comment]
Plaso 1.3.0 RC2 20150701
Running VT analysis plugin without providing VT api key yields a 403 client error from VT website. It is unclear to the user why this happens. If a user does not know he needs to provide a api key this can be very confusing as the error message is not clear. Imho a "missing api key error" should be raised first before even contacting VT servers.

**Comment by Onager** [comment]
Hmm, yes, that was the intention.

I'll look into while the error isn't being raised.
https://github.com/log2timeline/plaso/issues/249

-Daniel

**Comment by joachimmetz** [comment]
Moved remaining issues to separate issue trackers, closing this one.

**Comment by xhlika** [comment]
Was this " Add parser information to the "Unable to process path spec" bug if possible to make debugging easier" fixed? I am getting:


*********************************** Error: 0 ***********************************
           Message : Worker failed to process path specification
      Parser chain : None
                     C:\Users\xxxx\Desktop\xxx\xxx.E01
                   : type: EWF
                   : type: TSK, location: /
--------------------------------------------------------------------------------

*********************************** Error: 1 ***********************************
           Message : Worker failed to process path specification
      Parser chain : None
Path specification : type: OS, location:
                     C:\Users\xxx\xxx\xxx\xxx.E01
                   : type: EWF
                   : type: VSHADOW, location: /vss1, store index: 0
                   : type: TSK, location: /
--------------------------------------------------------------------------------

**Comment by xhlika** [comment]
@joachimmetz sorry about that. This GitHub issue was the only google search result that was linked to my issue. I think the version I am is relatively new version (seems 2019): plaso - log2timeline version 20190331. Any idea where the issue lies, I am simply running plaso with this command:

log2timeline -z UTC --status_view window --parsers "win7,-filestat" C:\Users\............\plaso_full.dump C:\Users\...........\x.E01

**Comment by joachimmetz** [comment]
> https://prnt.sc/1vyeksy it appears that after the "Main" worker, the next worker failed. The File column is saying "TSK:/".

What does pinfo tell you more about the error? (as the message suggests)

See here for tips on troubleshooting https://plaso.readthedocs.io/en/latest/sources/Troubleshooting.html

>  plaso - log2timeline version 20190331

This version (from March 2019) is older than 6 months so we consider it out of date and strongly recommend to update to a more recent version, including dependencies. Note that issues get addressed continously

**Comment by xhlika** [comment]
> What does pinfo tell you more about the error? (as the message suggests)

The first comment above was the output from pinfo (see above). The issue seems to be VSS. When I execute log2timeline and ignore the VSS, the parsing works (still ongoing). 

If you have no idea why VSS is causing this, then I can maybe try the update but I wonder if it will help. The issue should have been fixed in 2015 (at least based on this issue).

**Comment by joachimmetz** [comment]
`Worker failed to process path specification` is a generic catch all, typically debug logs contain more info. 

> The issue should have been fixed in 2015 (at least based on this issue).

what issue should be fixed in 2015? "Unable to process path spec" is not a bug its a warning that things could not be processed, there are many different reasons for this.

> If you have no idea why VSS is causing this

I have insufficient information. You'll need to be more specific and provide the information outlined in https://plaso.readthedocs.io/en/latest/sources/Troubleshooting.html
