### ISSUE TITLE
Create/Update release preparation script

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2281]
Create/Update release preparation script to:

* [x] ~~Update version~~
* [x] ~~update version and name of dmg in docs/sources/user/MacOS-Packaged-Release.md~~ - no longer applicable
* [x] ~~update version in docs/sources/user/Windows-Packaged-Release.md~~ - no longer applicable
* [x] ~~Update version dependent documentation (list of parsers and plugins). Also see: https://github.com/log2timeline/plaso/issues/2277~~
* [x] ~~Idea: Update output module documentation - moved to https://github.com/log2timeline/plaso/issues/3642~~
* [x] ~~Idea: Update AUTHORS - moved to https://github.com/log2timeline/plaso/issues/3643~~
