### ISSUE TITLE
Improve end-to-end testing

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#280]
- [x] ~~[create a Python-based end-to-end test script](https://codereview.appspot.com/279620043/)~~
- [x] ~~Make sure CI tests, test each end-to-end test case~~
  - ~~add test for "output"~~
  - ~~add test for "extract and output"~~
- [x] ~~psort and time slice functionality try to catch: https://github.com/log2timeline/plaso/issues/598~~
  - ~~needs output comparison test~~
- [x] ~~end-to-end "extract and compare" try to catch https://github.com/log2timeline/plaso/issues/556~~
- [x] ~~end-to-end test script add “output and analyze” test case~~ - moved to https://github.com/log2timeline/plaso/issues/1901
- [x] ~~end-to-end test script add “preg” test case~~ - moved to https://github.com/log2timeline/l2tpreg/issues/28
- [x] ~~set-up CI equivalent for end-to-end tests @Onager~~
- [x] ~~Update [wiki](https://github.com/log2timeline/plaso/wiki/Testing)~~
- [x] ~~create script(s) to generate test file~~
  - ~~test_data/*.plaso~~
- [x] ~~run psort tagging multiple times~~ - moved to https://github.com/log2timeline/plaso/issues/1903
- [x] ~~add tests for files with Unicode paths (see: https://github.com/log2timeline/plaso/issues/351)~~ - moved to test cases
- [x] ~~add tests for filter files (and other data files?)~~ - moved to test cases

**Comment by joachimmetz** [comment]
Not a 1.4 show stopper but working on this for the 1.4 release.
