### ISSUE TITLE
Implement task-based processing

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#338]
Overhaul worker to process in phases. The idea here is to make various parts less complex:

* multi processing
* handling of file entries vs. data streams

Overview:

* [Multi process task-based processing](https://github.com/joachimmetz/l2tdocs/blob/arch/architecture/Task-based%20processing.asciidoc)

Actions:

* [x] ~~Write a [proposal](https://github.com/log2timeline/l2tdocs/blob/master/design/Design%20proposal%20-%20phased%20processing.asciidoc)~~
* [x] ~~Fix end-to-end tests on Travis~~
* [x] ~~[Migrate to single attribute container serializer](https://github.com/log2timeline/plaso/issues/633)~~
* [x] ~~[Add event source attribute container](https://codereview.appspot.com/291600043/)~~
* [x] ~~[Split collector and queue producer](https://codereview.appspot.com/298920043/)~~
* [x] ~~[Added version information to storage](https://codereview.appspot.com/295100043/)~~
* [x] ~~[Write event sources to storage after collection](https://codereview.appspot.com/298080043/)~~
  * ~~Add event sources support to storage~~
  * ~~change zip file storage no longer refer to proto files~~
  * ~~read event sources from storage after collection~~
  * ~~ignore existing event sources in processing (storage writer)~~
  * ~~combine storage session with tool run session~~
* [x] ~~[Split storage writer and queue consumer](https://codereview.appspot.com/298130043/)~~
* [x] ~~[Moved event extraction from worker into separate extractor](https://codereview.appspot.com/300730043/)~~
* [x] ~~[Move collector to path spec extractor](http://codereview.appspot.com/300740043)~~
* [x] ~~[Add task based storage](https://codereview.appspot.com/299270043/)~~
* [x] ~~[ZIP storage file reader and task storage merge](https://codereview.appspot.com/298460043/)~~
* [x] ~~[Split worker and path spec consumer](https://codereview.appspot.com/301940043/)~~
  * ~~Remove queues from single processing~~
  * ~~Merge per worker storage files after extraction~~
  * ~~Create event object queue producer for analysis plugins~~
* [x] ~~[Moved directory recurse to worker and added task-based processing](https://codereview.appspot.com/295640043/)~~
  * ~~Add multi phase processing to process extracted path specs~~
  * ~~Refactor status information~~
  * ~~Move (part of) collector to worker~~
  * ~~Add task based multi processing~~
  * ~~Make task storage smaller and merge during extraction~~
* [x] ~~[Fix multi processing main process status view](https://codereview.appspot.com/296580043/)~~
* [x] ~~[psort make sure storage file is closed on error](https://codereview.appspot.com/299450043)~~
* [x] ~~storage: clean up #102~~
  * ~~rename `AddEventObject` to `AddEvent`~~
  * ~~Rename `StorageObject` to `BaseStorage`~~
* [x] ~~Make parser error queue operational #119~~
* [x] ~~Process completes but does not exit (leaving stranded workers) #399~~
* [x] ~~fixes for data stream support #378~~
* [x] ~~[Fix status reported on exit](https://codereview.appspot.com/303910043/) #755~~
* [x] ~~[Create session object](https://codereview.appspot.com/303910043/)~~
* [x] ~~[Create task object](https://codereview.appspot.com/296620043/)~~
* [x] ~~[Move storage merge into collection thread](http://codereview.appspot.com/302100043/)~~
* [x] ~~[Remove the need for ForceFlush](https://codereview.appspot.com/295700043/)~~
* [x] ~~[Test and handle abort paths](https://codereview.appspot.com/301140043/)~~
  * ~~reimplement debug hook~~
* [x] ~~[Fix process archive functionality](https://codereview.appspot.com/300570043/) #230~~
  * ~~revisit `_ProcessArchiveFile`~~
* [x] ~~[Handle unexpected worker process deaths](https://codereview.appspot.com/298650043/)~~
  * ~~test and handle kill of worker~~
  * ~~Print number of errors on exit~~
  * ~~Track which files were skipped - instead of printing it to stdout/stderr~~
* [x] ~~[Fix for task storage not completed on unexpected error](https://codereview.appspot.com/301180043/)~~
  * ~~handle "Detected unclosed task"~~
  * ~~add tests to make sure broken task storage files are handled correctly~~
* [x] ~~[Process metadata of symbolic links](https://codereview.appspot.com/302900043/) #437~~
* [x] ~~[move profiles to main and worker processes](https://codereview.appspot.com/302920043/) #773~~
* [x] ~~[Make task schedule thread main thread and move status updates to separate status thread](https://codereview.appspot.com/304740043/)~~
  * ~~Show last merged task storage in status information~~
* [x] ~~check if GetEventSourceByIndex working efficiently~~
* [x] ~~do not issue collection task for non directory path spec~~
* [x] ~~[Look into fixing abort path](https://codereview.appspot.com/307910043/)~~
  * ~~add missing attribute container tests~~
  * ~~Store IOErrors raised by ProcessPathSpec as extraction errors~~

**Comment by joachimmetz** [comment]
Change processing status tracking also see: https://codereview.appspot.com/273570043/
