### ISSUE TITLE
psort: clean up and improve

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#366]
Use this issue to track psort clean up and improvements efforts:
- [x] ~~Remove need to check for plaso_storage_pb2.EventObject~~
- [x] ~~[Move PsortAnalysisProcess to multi_processing](https://codereview.appspot.com/302250043/)~~
- [x] ~~[Move queue consumer out of analysis plugin](https://codereview.appspot.com/302260043/)~~
- [x] ~~[Split off engine from psort front-end](https://codereview.appspot.com/304220043/)~~
- [x] ~~[Replace analysis report queue by storage writer](https://codereview.appspot.com/307920043/)~~
- [x] ~~[Split analysis and export phase](https://codereview.appspot.com/304230043/)~~
- [x] ~~Fix event.EqualityString() approach it uses is broken by design~~
- [x] ~~Reduce the need to run psort multiple times #244~~
- [x] ~~check abort path of failing plugin - moved to https://github.com/log2timeline/plaso/issues/3309~~
- [x] ~~Fix abort path, send analyzer processes a sigterm - moved to https://github.com/log2timeline/plaso/issues/3309~~
- [x] ~~improve psort error output #500~~
- [x] ~~re-introduce pstorage output module? - not for now~~
- [x] ~~Reduce memory consumption - overall memory consumption under control to check individual analysis processes~~
- [x] ~~Add profiling~~
- [x] ~~Introduce AnalysisError - moved to https://github.com/log2timeline/plaso/issues/3396~~
- [x] ~~Determine if `use_time_slicer` can be deprecated - moved to https://github.com/log2timeline/plaso/issues/3397~~
- [x] ~~Add multi processing event or equiv to sleep main process while waiting for workers.~~
