### ISSUE TITLE
fixes for data stream support

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#378]
data stream support has surfaced some issues, this is the overall tracking bug for fixes and improvements

* [x] ~~[Winrestore: exception parsing data stream](https://github.com/log2timeline/plaso/issues/372)~~
  * ~~https://codereview.appspot.com/267420043/~~
  * ~~Introduce parser filters, to handle file name based parser selection outside of parser itself, also see filter-based winreg plugin approach~~
* [x] ~~[Split different parser types: chrome cache parser and filestat from syslog (and equiv) parsers](http://codereview.appspot.com/269460043)~~
* [x] ~~[Serializer: exception when deserializing pathspec](https://github.com/log2timeline/plaso/issues/371)~~
* [x] ~~Have hasher ignore [special files](https://github.com/log2timeline/plaso/issues/199)~~
