### ISSUE TITLE
Add more parsers

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#518]
The following information was taken from: [Plaso - Roadmap and Assignment](http://goo.gl/cRjA7y) which is DEPRECATED
- [x] ~~Flash Cookies (LSO/SOL)~~ moved to https://github.com/log2timeline/plaso/issues/2540
- [x] ~~Firefox Mork~~ moved to https://github.com/log2timeline/plaso/issues/2541
- [x] ~~[Google Drive client sync_log.log](https://github.com/log2timeline/plaso/issues/343)~~
- [x] ~~Mac OS X Notes.app~~ moved to https://github.com/log2timeline/plaso/issues/443
- [x] ~~MSIE DOMStorage~~ moved to https://github.com/log2timeline/plaso/issues/2543
- [x] ~~MSIE WebCache - add cookie parsing support~~ moved to https://github.com/log2timeline/plaso/issues/2544
- [x] ~~NTFS $Logfile~~ moved to https://github.com/log2timeline/plaso/issues/316
- [x] ~~Outlook email - PST/OST~~ moved to https://github.com/log2timeline/plaso/issues/2545
- [x] ~~Restore Points (addition) logs (e.g. change.log)~~ moved to https://github.com/log2timeline/plaso/issues/2546
- [x] ~~User Assist~~ moved to https://github.com/log2timeline/plaso/issues/2550
- [x] ~~Windows Desktop Search~~ moved to https://github.com/log2timeline/plaso/issues/2547
- [x] ~~Windows Event Log XML parser~~ moved to https://github.com/log2timeline/plaso/issues/442
- [x] ~~Windows .job files~~ moved to https://github.com/log2timeline/plaso/issues/2551
- [x] ~~Windows Media player database (WMDB)~~ moved to https://github.com/log2timeline/plaso/issues/2552
- [x] ~~[Windows 10 compressed Prefetch file](https://github.com/log2timeline/plaso/issues/234)~~
- [x] ~~Windows SetupAPI logs~~ moved to https://github.com/log2timeline/plaso/issues/2549
- [x] ~~Windows SuperFetch~~ moved to https://github.com/log2timeline/plaso/issues/2548
- [x] ~~[Windows System Resource Usage Monitor (SRUM) database](https://github.com/log2timeline/plaso/issues/427)~~
- [x] ~~Windows Task Scheduler XML files~~ moved to https://github.com/log2timeline/plaso/issues/259
- [x] ~~WMI Repository~~ moved to https://github.com/log2timeline/plaso/issues/179

**Comment by SleuthKid** [comment]
I would really love to see the Apache Log (and possibly error) parser from https://codereview.appspot.com/76230045/ brought to life again.

If the status of the original code by Marc Séguin allows this and there is a branch I can checkout I might have a look for an updated PR.

**Comment by joachimmetz** [comment]
> If the status of the original code by Marc Séguin allows this and there is a branch I can checkout I might have a look for an updated PR.

You can get the diff from here: https://codereview.appspot.com/download/issue76230045_40001.diff

A Change Request (PR) would be useful but please have a look at https://github.com/log2timeline/plaso/wiki/Developers-Guide since we are not fully using the github process, for reasons mentioned on the wiki page.

**Comment by joachimmetz** [comment]
@rhaist apache log parser was added in https://github.com/log2timeline/plaso/issues/2106. For additional feature request (FR) or changes to the apache log parser I recommend creating a new FR.

Closing this issue, in favor of newly created issues.
