### ISSUE TITLE
Add more analysis plugins

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#521]
The following information was taken from: [Plaso - Roadmap and Assignment](http://goo.gl/cRjA7y)
- [x] ~~time_changing; finds event logs for time changing as well as comparing log file times to file offsets (should be sequential)~~
-  [x] ~~win_system_user_anomaly; Detects abnormal activity for windows system accounts (sids from S-1-5-18 to 20) e.g. link files,internet history~~
- [x] ~~NSRL Server~~
- [x] ~~file_ext_stats; counts extensions, initially from LNK files and files. some proposed purposes are: detect interesting file types , categorize ext's, ~~
- [x] ~~usb_devices; Tracks USB key insertion in multiple locations (setupapi/registry/eventlog) and creates a report~~
- [x] ~~extract_metadata; extracts delimited files for manual analysis, e.g. for LNK files, usb devices, user-assist, Internet history for file:// entries, parsed recycle bin entries, etc.~~ moved to https://github.com/log2timeline/plaso/issues/2659
- [x] ~~top_website_domains; show top ten accessed domains from web history for computer overall and possibly also from each user.~~ moved to https://github.com/log2timeline/plaso/issues/2660
- [x] ~~lnk with different path and target link identifier (shell item list)~~ moved to https://github.com/log2timeline/plaso/issues/2661
- [x] ~~Windows services; detect anomaly in Windows services~~ moved to https://github.com/log2timeline/plaso/issues/2662

**Comment by joachimmetz** [comment]
Issue split across other issues.
