### ISSUE TITLE
Pinfo ouput about parsers misleading

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#724]
**Plaso version:** HEAD

**Description of problem:**

Preprocessing output detects Windows correctly, but all parsers are enabled, rather than just Windows ones.

**Debug output/tracebacks:**
```
<windows> [PreProcess] Set attribute: osversion to Windows 7 Enterprise
```

But from pinfo on the storage file:
```
        parsers = android_app_usage, asl_log, bencode, binary_cookies, bsm_log, chrome_cache, chrome_preferences, cups_ipp, custom_destinations, dockerjson, esedb, filestat, firefox_cache, firefox_cache2, hachoir, java_idx, lnk, mac_appfirewall_log, mac_keychain, mac_securityd, mactime, macwifi, mcafee_protection, mft, msiecf, olecf, openxml, opera_global, opera_typed_history, pe, plist, pls_recall, popularity_contest, prefetch, recycle_bin, recycle_bin_info2, rplog, sccm, selinux, skydrive_log, skydrive_log_old, sqlite, symantec_scanlog, syslog, usnjrnl, utmp, utmpx, winevt, winevtx, winfirewall, winiis, winjob, winreg, xchatlog, xchatscrollback
```

**TODO:**

* [x] ~~Print details about extraction errors~~
* [x] ~~Change pinfo output~~
  * ~~fix "Source processed" N/A in pinfo test~~
  * ~~fix "protobuf_size = 0" in pinfo test~~
* [x] ~~[Clean up of pinfo](https://codereview.appspot.com/304130043/)~~
  * ~~changed parsers list to enabled parsers~~

**Comment by joachimmetz** [comment]
What is the exact issue here?
* are all parsers selected?
* Or are just the name of all parsers stored in the storage file?

**Comment by Onager** [comment]
From user reports, all parsers were selected. This needs more investigation though.

**Comment by Onager** [comment]
I took at look at this just now, and it seems like the initial reports weren't correct, and not all parsers are being run, just the wrong names stored in the storage file.

**Comment by joachimmetz** [comment]
I'll address this as part of task-based processing changes
