### ISSUE TITLE
Google analytics cookie parser produces invalid timestamps.

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#727]
**Plaso version:**
20160603 HEAD

**Operating system Plaso is running on:**

N/A

**Installation method:**

N/A

**Description of problem:**

Google analytics cookie parser is producing invalid timestamps. Looks like a change in the date format.

**Debug output/tracebacks:**

```[ERROR] Event: 10:183877 data type: cookie:google:analytics:utmb display name: TSK:/Users/admin/Library/Cookies/Cookies.binarycookies parser chain: binary_cookies/google_analytics_utmb with error: unable to copy timestamp: 1440489514899000000 to a human readable date and time with error: date value out of range. Defaulting to: "0000-00-00T00:00:00"```

**Source data:**

From the dean_mac test image.

**TODO:**

* [x] ~~[Update cookies parser to handle different cookie formats](https://codereview.appspot.com/305840043/)~~
* [x] Get copy of /Users/admin/Library/Cookies/Cookies.binarycookies
* [x] Check Cookies.binarycookies

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/305840043/

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/302380043/
