### ISSUE TITLE
efilter multiple filtering errors and warnings

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#820]
**Plaso version:** HEAD

filter query:
```
repeated
  body contains 'last message repeated'
```

error:
```
EfilterTypeError: EfilterTypeError (All values in a repeated value must be of the same type.)
in query "(if 'last message repeated' in body then 'repeated')"
```

contents of self._tag_rules
```
Repeat(IfElse(
 Union(Membership(
  Literal('last message repeated')
  Var('body')))
 Literal('repeated')
 Literal(None)))
```

`Repeat` this efilter statement seems to be not behaving as expected.

**TODO**:

* [x] ~~[prevent incorrect efilter expression breaking the analysis plugin](http://codereview.appspot.com/306780043)~~
* [ ] Fix incorrect efilter expression being generated
* [ ] add filter to test file

**Comment by joachimmetz** [comment]
Looks to be related to "contains" (`Membership`) within `Repeat`

**Comment by Onager** [comment]
This seems to occur when trying to test if ````None``` contains a string.

**Comment by Onager** [comment]
The exception is due to efilter trying to iterate over `None`. Filed https://github.com/google/dotty/issues/21

We can also work around this by returning an iterable type here: https://github.com/log2timeline/plaso/blob/master/plaso/containers/interface.py#L62 instead of `None`

**Comment by joachimmetz** [comment]
Fix blocked by upstream

**Comment by joachimmetz** [comment]
```
psort.py --log-file=test.log --analysis tagging --tagging-file data/tag_windows.txt -o null test.plaso
```

Floods the output with approximate 356220 errors: `All values in a repeated value must be of the same type.`
```
[WARNING] Unable to apply efilter query with error: EfilterTypeError (All values in a repeated value must be of the same type.) in query "(if data_type == 'windows:prefetch' or data_type == 'windows:lnk:link' and 'Recent' in filename and ('.exe' in local_path or '.exe' in network_path or '.exe' in relative_path) or data_type == 'windows:registry:key_value' and ('userassist' in plugin or 'mru' in plugin) and '.exe' in regvalue.__all__ or data_type == 'windows:evtx:record' and 'user mode service' in strings and 'demand start' in strings or data_type == 'fs:stat' and 'Windows/Tasks/At' in filename or data_type == 'windows:tasks:job' or data_type == 'windows:evt:record' and source_name == 'Security' and event_identifier == 592 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Security-Auditing' and event_identifier == 4688 or data_type == 'windows:registry:appcompatcache' then 'application_execution', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Application-Experience' and event_identifier == 903 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Application-Experience' and event_identifier == 904 then 'application_install', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Application-Experience' and event_identifier == 905 then 'application_update', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Application-Experience' and event_identifier == 907 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Application-Experience' and event_identifier == 908 then 'application_removal', if data_type == 'windows:registry:key_value' and 'mru' in plugin and '.exe' not in regvalue.__all__ and timestamp > 0 then 'document_open', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Security-Auditing' and event_identifier == 4625 then 'login_failed', if data_type == 'windows:evt:record' and source_name == 'Security' and event_identifier == 540 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Security-Auditing' and event_identifier == 4624 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-TerminalServices-LocalSessionManager' and event_identifier == 21 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-TerminalServices-LocalSessionManager' and event_identifier == 1101 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Winlogon' and event_identifier == 7001 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-TerminalServices-RemoteConnectionManager' and event_identifier == 1147 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-TerminalServices-RemoteConnectionManager' and event_identifier == 1149 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-User Profiles Service' and event_identifier == 2 then 'login_attempt', if data_type == 'windows:evt:record' and source_name == 'Security' and event_identifier == 538 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Security-Auditing' and event_identifier == 4634 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Winlogon' and event_identifier == 7002 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-TerminalServices-LocalSessionManager' and event_identifier == 23 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-TerminalServices-LocalSessionManager' and event_identifier == 1103 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-User Profiles Service' and event_identifier == 4 then 'logoff', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-TerminalServices-LocalSessionManager' and event_identifier == 24 then 'session_disconnection', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-TerminalServices-LocalSessionManager' and event_identifier == 25 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-TerminalServices-LocalSessionManager' and event_identifier == 1105 then 'session_reconnection', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-TerminalServices-LocalSessionManager' and event_identifier == 22 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-TerminalServices-LocalSessionManager' and event_identifier == 1102 then 'shell_start', if data_type == 'windows:evt:record' and source_name == 'Security' and event_identifier == 602 or data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Security-Auditing' and event_identifier == 4698 then 'task_schedule', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-TaskScheduler' and event_identifier == 102 then 'job_success', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-TaskScheduler' and event_identifier == 201 then 'action_success', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-DNS-Client' and event_identifier == 1014 then 'name_resolution_timeout', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Kernel-General' and event_identifier == 1 then 'time_change', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Kernel-General' and event_identifier == 13 then 'shutdown', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Kernel-General' and event_identifier == 13 then 'system_start', if data_type == 'windows:evtx:record' and source_name == 'Microsoft-Windows-Kernel-Power' and event_identifier == 42 then 'system_sleep', if data_type == 'windows:registry:key_value' and 'Run' in plugin or data_type == 'windows:registry:key_value' and ('run' in plugin or 'lfu' in plugin) and ('.exe' in regvalue.__all__ or '.dll' in regvalue.__all__) then 'autorun', if data_type == 'chrome:history:file_downloaded' or timestamp_desc == 'File Downloaded' then 'file_download', if (data_type == 'metadata:hachoir' or data_type == 'olecf:summary_info') and 'Printed' in timestamp_desc then 'document_print')"
```

**Comment by joachimmetz** [comment]
Efilter 1.4 should address the issue.
